### ISSUE TITLE
 /spending_female_3_orders_agg - Luis

### ISSUE THREAD

**Issue by ferreiro** [ferreiro/Python_NoSQL#16]

**Comment by ferreiro** [comment]
Hi Luis. I write a comment on your commit (https://github.com/ferreiro/Python_NoSQL/commit/2dad2690bf07791dcd21612ecc9d2537d56d7b9b).

The idea is ok, but is not the correct way to work with map/reduce. You can check in the current code how to do this.

Bye.

**Comment by luisdeol** [comment]
Oh, I got it, Thank you.
